# Generated by Django 5.2 on 2025-04-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='phase',
            field=models.CharField(choices=[('emphatize', 'Emphatize'), ('define', 'Define'), ('ideate', 'Ideate'), ('prototype', 'Prototype'), ('test', 'Test')], default='emphatize', max_length=20),
        ),
    ]
